---
# Source: kubeeye/templates/inspect-result.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-name-kubeeye-inspect-result
  labels:
    helm.sh/chart: kubeeye-1.0.0
    app.kubernetes.io/name: kubeeye
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  volumeMode: Filesystem
