---
# Source: kubeeye/templates/manager-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-kubeeye-manager-config
  labels:
    helm.sh/chart: kubeeye-1.0.0
    app.kubernetes.io/name: kubeeye
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  controller_manager_config.yaml:  |-
   apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
   kind: ControllerManagerConfig
   health:
     healthProbeBindAddress: :8081
   metrics:
     bindAddress: 127.0.0.1:8080
   webhook:
     port: 9443
   leaderElection:
     leaderElect: true
     resourceName: fa68b2a3.kubesphere.io
