---
# Source: kubeeye/templates/metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubeeye-controller-manager-metrics-service
  labels:
    control-plane: kubeeye-controller-manager
    helm.sh/chart: kubeeye-1.0.0
    app.kubernetes.io/name: kubeeye
    app.kubernetes.io/instance: kubeeye
    app.kubernetes.io/version: "v1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    control-plane: kubeeye-controller-manager
    app.kubernetes.io/name: kubeeye
    app.kubernetes.io/instance: kubeeye
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
