global:
  imageRegistry: "easzlab.io.local:5000"
  # default to use "local-path-provisioner"
  storageClass: "{{ kubeapps_storage_class }}"

## @section Kubeapps packaging options
packaging:
  helm:
    enabled: true
  carvel:
    enabled: false
  flux:
    enabled: false

## @section Frontend parameters
frontend:
  image:
    repository: bitnami/nginx
    tag: 1.23.4-debian-11-r18
  replicaCount: 1
  service:
    type: NodePort

## @section Dashboard parameters
dashboard:
  enabled: true
  image:
    repository: bitnami/kubeapps-dashboard
    tag: 2.7.0-debian-11-r12
  replicaCount: 1 

## @section AppRepository Controller parameters
apprepository:
  image:
    repository: bitnami/kubeapps-apprepository-controller
    tag: 2.7.0-scratch-r0
  syncImage:
    repository: bitnami/kubeapps-asset-syncer
    tag: 2.7.0-scratch-r0
  initialRepos:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami
  ## @param apprepository.crontab Default schedule for syncing App repositories
  crontab: "*/10 * * * *"
  watchAllNamespaces: true
  replicaCount: 1

## Auth Proxy configuration for OIDC support
authProxy:
  enabled: false

## @section Other Parameters
clusters:
  - name: default
    domain: cluster.local

## @section Database Parameters
postgresql:
  enabled: true
  auth:
    username: "postgres"
    postgresPassword: "Postgres1234!"
    database: assets
    existingSecret: ""
  primary:
    persistence:
      enabled: true 
  architecture: standalone

## @section kubeappsapis parameters
kubeappsapis:
  image:
    repository: bitnami/kubeapps-apis
    tag: 2.7.0-debian-11-r10
  replicaCount: 1
