kubernetesClusterDomain: cluster.local
rocketmqOperator:
  manager:
    args:
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
    env:
      operatorName: rocketmq-operator
    image:
      repository: apache/rocketmq-operator
      tag: latest
    imagePullPolicy: IfNotPresent
  replicas: 1
  serviceAccount:
    annotations: {}
  resources:
    limits:
      cpu: 2
      memory: 10Gi
    requests:
      cpu: 2
      memory: 10Gi