apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    name: k8s-yaml-bak
  name: k8s-yaml-bak
  namespace: 
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          serviceAccountName: k8s-yaml-bak-sa
          containers:
            - name: k8s-yaml-bak
              image: //:
              imagePullPolicy: IfNotPresent
              args:
              - "--git-url"
              - ""
              - "--local-dir"
              - "/tmp/prod-clusterdump/"
              - "--exclude-having-owner-ref"
              - "--exclude-kind"
              - "events,nodes,replicasets"
              - "--dump-only"
              - "--exclude-object"
              - "configmap:kube-system/leader-elector"
              - "-p"
              - "8888"
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: ""
  successfulJobsHistoryLimit: 1
  suspend: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-yaml-bak-sa
  namespace: 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-cronjob-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cronjob-role-binding
subjects:
  - kind: ServiceAccount
    name: k8s-yaml-bak-sa
    namespace: 
roleRef:
  kind: ClusterRole
  name: my-cronjob-role
  apiGroup: rbac.authorization.k8s.io