apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-problem-detector
  namespace: "{{ npd_install_namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: npd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-problem-detector
subjects:
  - kind: ServiceAccount
    name: node-problem-detector
    namespace: "{{ npd_install_namespace }}"