apiVersion: batch/v1
kind: CronJob
metadata:
  name: nacos-test
  namespace: "kube-system"
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 0
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - |
              curl -sS --fail --connect-timeout 5 -X POST 'http://nacos-headless-stand.olprod.svc.cluster.local:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'
              curl -sS --fail --connect-timeout 5 -X GET 'http://nacos-headless-stand.olprod.svc.cluster.local:8848/nacos/v1/ns/instance/list?serviceName=nacos.naming.serviceName' | grep "20.18.7.10"
              if [ $? -eq 0 ]; then
                echo "  successfully"
              else
                echo "   ERROE"
                exit 1
              fi
            command:
            - /bin/sh
            - -c
            image: xxx.com/easzlab/alpine-curl:v7.85.0
            imagePullPolicy: IfNotPresent
            name: nacos-test
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
