apiVersion: batch/v1
kind: CronJob
metadata:
  name: rocketmq-test
  namespace: "kube-system"
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 0
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - |
              NAMESRV_ADDR="rocketmq-namesrv.olprod:9876"
              TOPIC="TestTopic"
              bin/mqadmin updateTopic -n $NAMESRV_ADDR -c DefaultCluster -t $TOPIC
              if [ $? -eq 0 ]; then
                echo "Topic $TOPIC created successfully"
              else
                echo "Failed to create topic $TOPIC"
                exit 1
              fi
              bin/mqadmin sendMessage -n $NAMESRV_ADDR -c DefaultCluster -t $TOPIC -p "Hello, RocketMQ" &
              sleep 5
              bin/mqadmin consumeMessage -n $NAMESRV_ADDR  -t $TOPIC  | grep "Hello, RocketMQ"
              if [ $? -eq 0 ]; then
                echo "Messages consumed successfully"
              else
                echo "Failed to consume messages"
                exit 1
              fi
              sleep 5
              bin/mqadmin deleteTopic -n $NAMESRV_ADDR -c DefaultCluster -t $TOPIC
              if [ $? -eq 0 ]; then
                echo "Topic $TOPIC deleted successfully"
              else
                echo "Failed to delete topic $TOPIC"
                exit 1
              fi
            command:
            - /bin/bash
            - -c
            image: xxx.com/devops-tool/rocketmq-4.9.2:v1
            imagePullPolicy: IfNotPresent
            name: rocketmq-test-container
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
