apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    grp: ops-tasks
    job: network-check
    name: reids-test
  name: reids-test
  namespace: "kube-system"
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 0
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - sh
            - -c
            - redis-cli -h redis-service.ptp-prod.svc  -p 6379 -a 'Ctc1qa2ws!@2020%778!#'  ping
            image: chinamobile.com/zsf/redis:latest
            imagePullPolicy: IfNotPresent
            name: reids-test
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
