---
# Source: gateway/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-1.23.2
    app: istio-ingress
    istio: ingress
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/version: "1.23.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingress
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
