---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-1.23.2
    app: istio-ingress
    istio: ingress
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/version: "1.23.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-1.23.2
    app: istio-ingress
    istio: ingress
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/version: "1.23.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-ingress
subjects:
- kind: ServiceAccount
  name: istio-ingress
