---
# Source: gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-1.23.2
    app: istio-ingress
    istio: ingress
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/version: "1.23.2"
    app.kubernetes.io/managed-by: Helm
