---
# Source: gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name
  namespace: default
  labels:
    helm.sh/chart: gateway-1.23.2
    app: release-name
    istio: release-name
    app.kubernetes.io/name: release-name
    app.kubernetes.io/version: "1.23.2"
    app.kubernetes.io/managed-by: Helm
