---
# Source: node-problem-detector/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: npd-node-problem-detector
  labels:
    app.kubernetes.io/name: node-problem-detector
    helm.sh/chart: node-problem-detector-2.3.14
    app.kubernetes.io/instance: npd
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: npd-node-problem-detector
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: npd-node-problem-detector
  apiGroup: rbac.authorization.k8s.io
