---
# Source: pxc-operator/templates/role-binding.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-pxc-operator
  namespace: mysql-operator
---
# Source: pxc-operator/templates/role-binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysql-operator-pxc-operator
  namespace: mysql-operator
  labels:
    app.kubernetes.io/name: pxc-operator
    helm.sh/chart: pxc-operator-1.15.0
    app.kubernetes.io/instance: mysql-operator
    app.kubernetes.io/version: "1.15.0"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: mysql-operator-pxc-operator
roleRef:
  kind: Role
  name: mysql-operator-pxc-operator
  apiGroup: rbac.authorization.k8s.io
