#!/bin/bash

## 渲染 templates 的模板并显示生成的 Kubernetes 资源文件，但不应用到集群。



set -a  #加载到环境变量,下面的命令
#加载公共模块
. ../tasks/lib.sh
base_dir='..'


for env_var in $(grep -v '^#' "$base_dir"/vars/global_vars | grep -v '^\s*$'); do

    for file in "$base_dir"/vars/$env_var/*; do
        [ -e "$file" ] || fn_log_error "$file 配置文件不存在"  # 检查文件是否存在
        filename=$(basename "$file") # 获取变量的文件名
        
        echo -e "\033[35m   $filename 正在生成yaml文件.... 环境:$env_var \033[0m"
        fn_j2_to_files
        if [ -f ${base_dir}/manifests/${env_var}/${filename}/values.yaml ];then
        (
            . $file
            helm template ${release_name} -n ${namespace} -f  ${base_dir}/manifests/${env_var}/${filename}/values.yaml  ${base_dir}/files/${filename}-${chart_ver}.tgz  --output-dir  ${base_dir}/manifests/${env_var}/${filename}
        )
        fi   
        sleep 1
    done

done