---
# Source: nacos-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nacos-operator
  labels:
    helm.sh/chart: nacos-operator-0.1.0
    app.kubernetes.io/name: nacos-operator
    app.kubernetes.io/instance: nacos-operator
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: nacos-operator/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nacos-operator
rules:
  - apiGroups:
      - nacos.io
    resources:
      - nacos
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nacos.io
    resources:
      - nacos/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
      - apps
      - batch
    resources:
      - configmaps
      - statefulsets
      - pods
      - services
      - events
      - jobs
    verbs:
      - get
      - create
      - update
      - patch
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
      - patch
      - list
      - watch
---
# Source: nacos-operator/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nacos-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nacos-operator
subjects:
  - kind: ServiceAccount
    name: nacos-operator
    namespace: nacos-operator
