---
# Source: argo-cd/charts/redis-ha/templates/redis-haproxy-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-cd-redis-ha-haproxy
  namespace: "argo-cd"
  labels:
    app: redis-ha
    heritage: "Helm"
    release: "argo-cd"
    chart: redis-ha-4.27.6
    component: argo-cd-redis-ha-haproxy
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
