---
# Source: argo-cd/charts/redis-ha/templates/redis-ha-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-cd-redis-ha
  namespace: "argo-cd"
  labels:
    app: redis-ha
    heritage: "Helm"
    release: "argo-cd"
    chart: redis-ha-4.27.6
subjects:
- kind: ServiceAccount
  name: argo-cd-redis-ha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-cd-redis-ha
