---
# Source: argo-cd/charts/redis-ha/templates/redis-ha-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argo-cd-redis-ha-server
  namespace: "argo-cd"
  labels:
    argo-cd-redis-ha: replica
    app: redis-ha
    heritage: "Helm"
    release: "argo-cd"
    chart: redis-ha-4.27.6
  annotations:
    {}
spec:
  selector:
    matchLabels:
      release: argo-cd
      app: redis-ha
  serviceName: argo-cd-redis-ha
  replicas: 3
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/init-config: 95eff62a33be3de67ac0593b14f662c8a8a2308d749049f6b112f1406094237c
      labels:
        release: argo-cd
        app: redis-ha
        argo-cd-redis-ha: replica
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: redis-ha
                  release: argo-cd
                  argo-cd-redis-ha: replica
              topologyKey: kubernetes.io/hostname
      securityContext: 
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: argo-cd-redis-ha
      automountServiceAccountToken: false
      initContainers:
      - name: config-init
        image: public.ecr.aws/docker/library/redis:7.2.4-alpine
        imagePullPolicy: IfNotPresent
        resources:
          {}
        command:
        - sh
        args:
        - /readonly-config/init.sh
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault        
        env:
        - name: SENTINEL_ID_0
          value: 4794d0beec6abdd90a3821f7d9bf66804f290941
        - name: SENTINEL_ID_1
          value: c524e76c625cc68c94f25c99e20efce31df6f4c2
        - name: SENTINEL_ID_2
          value: 2f679f20284b54ed430b97819302f9dc0d48cb09
        - name: AUTH
          valueFrom:
            secretKeyRef:
              name: argocd-redis
              key: auth
        volumeMounts:
        - name: config
          mountPath: /readonly-config
          readOnly: true
        - name: data
          mountPath: /data


      containers:
      - name: redis
        image: public.ecr.aws/docker/library/redis:7.2.4-alpine
        imagePullPolicy: IfNotPresent
        command:
          - redis-server
        args:
          - /data/conf/redis.conf
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: AUTH
          valueFrom:
            secretKeyRef:
              name: argocd-redis
              key: auth
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
              - sh
              - -c
              - /health/redis_liveness.sh
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
              - sh
              - -c
              - /health/redis_readiness.sh
        resources:
          {}
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: config
          mountPath: /readonly-config
          readOnly: true
        - mountPath: /data
          name: data
        - mountPath: /health
          name: health
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - /readonly-config/trigger-failover-if-master.sh
      - name: sentinel
        image: public.ecr.aws/docker/library/redis:7.2.4-alpine
        imagePullPolicy: IfNotPresent
        command:
          - redis-sentinel
        args:
          - /data/conf/sentinel.conf
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: AUTH
          valueFrom:
            secretKeyRef:
              name: argocd-redis
              key: auth
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
              - sh
              - -c
              - /health/sentinel_liveness.sh
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 15
          successThreshold: 3
          failureThreshold: 5
          exec:
            command:
              - sh
              - -c
              - /health/sentinel_liveness.sh
        resources:
          {}
        ports:
          - name: sentinel
            containerPort: 26379
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /health
          name: health
        lifecycle:
          {}

      - name: split-brain-fix
        image: public.ecr.aws/docker/library/redis:7.2.4-alpine
        imagePullPolicy: IfNotPresent
        command:
          - sh
        args:
          - /readonly-config/fix-split-brain.sh
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault        
        env:
        - name: SENTINEL_ID_0
          value: 4794d0beec6abdd90a3821f7d9bf66804f290941
        - name: SENTINEL_ID_1
          value: c524e76c625cc68c94f25c99e20efce31df6f4c2
        - name: SENTINEL_ID_2
          value: 2f679f20284b54ed430b97819302f9dc0d48cb09
        - name: AUTH
          valueFrom:
            secretKeyRef:
              name: argocd-redis
              key: auth
        resources:
          {}
        volumeMounts:
        - name: config
          mountPath: /readonly-config
          readOnly: true
        - mountPath: /data
          name: data
      volumes:
      - name: config
        configMap:
          name: argo-cd-redis-ha-configmap
      - name: health
        configMap:
          name: argo-cd-redis-ha-health-configmap
          defaultMode: 0755
      - name: data
        emptyDir:
          {}
