name: k8s addon

on:
  push:
    branches:
      - main  # 根据需要调整分支名称
  workflow_dispatch:  # 添加手动触发

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          pass: ${{ secrets.PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 60s
          first_ssh: |-
            rm -rf /etc/K8sAddon/*
            mkdir -p /etc/K8sAddon/
          scp: |-
            './*' => /etc/K8sAddon/
          last_ssh: |-
            chmod +x /etc/K8sAddon/tasks/*.sh
            cd /etc/K8sAddon/
            sh tasks/deploy.sh