name: k8s addon

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  workflow_dispatch:  # Enable manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compress files for transfer
        run: tar -czf k8s_addon.tar.gz files tasks templates tools vars

      - name: Deploy to remote server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          pass: ${{ secrets.PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 60s
          first_ssh: |-
            rm -rf ~/.K8sAddon/
            mkdir -p ~/.K8sAddon/
          scp: |-
            './k8s_addon.tar.gz' => ~/.K8sAddon/
          last_ssh: |-
            cd ~/.K8sAddon/
            tar -xzf k8s_addon.tar.gz
            chmod +x tasks/*
            chmod +x tools/*
            sh tasks/deploy.sh
            rm -rf k8s_addon.tar.gz
