apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    image: chinamobile.com/zsf/redis:6.0-alpine
    imagePullPolicy: IfNotPresent
  redis:
    replicas: 3
    image: chinamobile.com/zsf/redis:6.0-alpine
    imagePullPolicy: IfNotPresent